import type { MetadataRoute } from 'next';
import { fetchRecentJobsServerSide } from '@/lib/jobs-server';
import { SITE_URL } from '@/lib/site-config';

/**
 * Dynamic sitemap: static core pages plus the newest active job listings.
 * Regenerated by Next.js on-demand per its own caching rules; job data itself
 * is revalidated hourly (see `fetchRecentJobsServerSide`).
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const now = new Date();

  const staticRoutes: MetadataRoute.Sitemap = [
    { url: SITE_URL, lastModified: now, changeFrequency: 'daily', priority: 1 },
    { url: `${SITE_URL}/jobs`, lastModified: now, changeFrequency: 'hourly', priority: 0.9 },
    { url: `${SITE_URL}/pricing`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    // Requires auth and is personalized, but listed as requested — search
    // engines will simply see the logged-out state (a login prompt), not any
    // user's saved jobs.
    { url: `${SITE_URL}/saved-jobs`, lastModified: now, changeFrequency: 'monthly', priority: 0.3 },
  ];

  const jobs = await fetchRecentJobsServerSide();
  const jobRoutes: MetadataRoute.Sitemap = jobs.map((job) => ({
    url: `${SITE_URL}/jobs/${job.slug}`,
    lastModified: job.postedAt ? new Date(job.postedAt) : new Date(job.createdAt),
    changeFrequency: 'daily',
    priority: 0.7,
  }));

  return [...staticRoutes, ...jobRoutes];
}
